name: "Construir y Publicar App"

on:
  release:
    types: [created] # Esto lo hará automático en el futuro
  workflow_dispatch: # Esto te permite darle al botón a mano por si acaso

jobs:
  build-tauri:
    permissions:
      contents: write # Permiso obligatorio para subir los .exe
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Instalar dependencias de Linux
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Instalar dependencias del Frontend
        run: npm install

      - name: Compilar Tauri y subir al Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
